.\" Manpage for manjaro-sway.

.TH man 8 "27 Dec 2020" "1.0" "Manjaro Sway Edition man page"

.SH NAME
Manjaro Sway Edition

.SH SHORTCUTS
Default Modifier: 
.B Super

New Terminal: 
.I mod
+ 
.B Enter

Application Launcher:
.I mod
+
.B d

Resize Mode:
.I mod
+ 
.B r

Screenshot Mode:
.I mod
+ 
.B Shift
+
.B s

Recording Mode:
.I mod
+
.B Shift
+
.B r

Move Window to Workspace:
.I mod
+
.B Shift
+
.I [number]

Switch to Workspace:
.I mod
+
.I [number]

Kill window:
.I mod
+
.B Shift
+
.B q

Toggle Floating:
.I mod
+
.B Shift
+
.B Space

Drag/Move window:
.I mod
+
.B Shift
+
.I [arrow]

Navigate Windows:
.I mod
+
.I [arrow]

Fullscreen:
.I mod
+
.B f


Exit:
.I mod
+
.B Shift
+
.B e

Open Help Overlay:
.I mod
+
.B Shift
+
.B ?

Close Help Overlay:
.B q

.SH UTILS

.B yay
Package manager

.B qutebrowser
keyboard centric browser

.B pulsemixer
audio mixer

.B nmtui
network manager

.B mpsyt
youtube player

.B ranger
file manager

.SH EXTEND

Logic should be injected into ~/.config/sway/config

.SH AUTHOR
Jonas Strassel (info@jonas-strassel.de)
