name: prepare
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
env:
  BUILD_DIR: /builder/build
  REPO_DIR: /builder/repository
  EXTRA_KEYS: 9C825A6605D40BBE 3BB639E56F861FA2E86505690FDD682D974CA72A A66D805F7C9329B4C5D82767CCC4F07FAC641EFF

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: docker://boredland/arch-builder:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: build
        run: |
          rm -rf /usr/include/crypt.h /usr/lib/libcrypt.so
          gpg --keyserver keyserver.ubuntu.com --recv-keys ${EXTRA_KEYS}
          pacman-key --keyserver keyserver.ubuntu.com --recv-keys ${EXTRA_KEYS}
          mkdir -p ${BUILD_DIR} && chown -R builder:builder ${BUILD_DIR}
          sudo -u builder yay -Sy --builddir ${BUILD_DIR} --noconfirm --nopgpfetch $(cat packages.txt | tr -s '\n' ' ')
      - name: prepare_gh_pages
        run: |
          ARCH=`uname -a | sed -E 's/.+ (.+) .+/\1/'`
          OWNER=${GITHUB_REPOSITORY%/*}
          REPO=${GITHUB_REPOSITORY##*/}
          ls -l ${BUILD_DIR}/**/*tar*
          rm -rf ${REPO_DIR}
          mkdir -p ${REPO_DIR}/${ARCH}
          cd ${REPO_DIR}/${ARCH}
          find ${BUILD_DIR} -name *.pkg.tar.zst -exec cp -f {} . \;
          repo-add ${OWNER}.db.tar.gz *.pkg.tar.zst
          ls ${REPO_DIR}/${ARCH}/*
          mv ${REPO_DIR} $GITHUB_WORKSPACE/gh-pages
          cp $GITHUB_WORKSPACE/index.template.html $GITHUB_WORKSPACE/gh-pages/index.html
          sed -i "s/OWNER/${OWNER}/g" $GITHUB_WORKSPACE/gh-pages/index.html
          sed -i "s/REPO/${REPO}/g" $GITHUB_WORKSPACE/gh-pages/index.html
          sed -i "s/TIMESTAMP/$(date)/g" $GITHUB_WORKSPACE/gh-pages/index.html
      - name: deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
